#!/usr/bin/env python3
import dashio
import json
import sys
import os

c64_filename = sys.argv[1]
json_filename = os.path.splitext(c64_filename)[0] + ".json"
try:
    with open(c64_filename, mode="r") as fp:
        cfg64 = fp.read()

except FileNotFoundError:
    print("File not found")

# Remove formatting for different languages
cfg64 = cfg64.translate({ord(i): None for i in '"\n \\;'})

print(cfg64)
config_dict = dashio.decode_cfg64(cfg64)
cfg_json = json.dumps(config_dict, indent=4)
print(cfg_json)

json_file = open(json_filename, "w")
json_file.write(cfg_json)
json_file.close()
